baseurl: /ember-app-kit

guides:
  - name: "Overview"
    page: "/"
  - name: "Getting Started"
    page: "/guides/getting-started.html"
  - name: "Using Modules &amp; the Resolver"
    page: "/guides/using-modules.html"
  - name: "Asset Compilation"
    page: "/guides/asset-compilation.html"
  - name: "Testing with Karma"
    page: "/guides/testing.html"
  - name: "Managing Dependencies"
    page: "/guides/dependencies.html"
  - name: "Deploying Your App"
    page: "/guides/deployment.html"
  - name: "Using With Ember Data"
    page: "/guides/ember-data.html"
  - name: "Mock and proxy requests"
    page: "/guides/mock-and-proxy-requests.html"
  - name: "Naming Conventions"
    page: "/guides/naming-conventions.html"
  - name: "Frequently Asked Questions"
    page: "/guides/faq.html"

pygments: true

exclude: [dist, node_modules, vendor, tmp]
